trigger:
  branches:
    include: ["master", "*"]
  paths:
    exclude: ["*.md"]

queue:
  name: Hosted VS2017
  timeoutInMinutes: 60

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: "**/*.csproj"
- task: MS-RichCodeNav.Indexer.build-task.RichCodeNavIndexer@0
  displayName: Rich Code Navigation Upload to Dev
  inputs:
    languages: 'csharp'
    githubServiceConnection: 'noellelc'
    environment: 'development'
    nugetFeed: 'https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-buildservices-staging@Local/nuget/v3/index.json'
  continueOnError: true