# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include: ["master", "*"]
  paths:
    exclude: ["*.md"]

queue:
  name: Hosted VS2017
  timeoutInMinutes: 60
  
steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.x
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: "**/*.csproj"
- task: UseDotNet@2
  displayName: 'Switch back to 2.0 Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 2.x
- task: MS-RichCodeNav.Indexer.build-task.RichCodeNavIndexer@0
  displayName: Rich Code Navigation Upload to Dev
  inputs:
    languages: 'csharp'
    githubServiceConnection: 'noellelc'
    environment: development
    nugetVersion: '0.1.1382-alpha'
    nugetFeed: 'https://devdiv.pkgs.visualstudio.com/Personal/_packaging/richnav/nuget/v3/index.json'
    isPrivateFeed: true
  continueOnError: true
