# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include: ["master", "*"]
  paths:
    exclude: ["*.md"]

queue:
  name: Hosted VS2017
  timeoutInMinutes: 60
  
steps:
- script: echo Starting build...
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: "**/*.csproj"
- task: MS-RichCodeNav.Indexer.build-task.RichCodeNavIndexer@0
  displayName: Rich Code Navigation Upload to Staging
  inputs:
    serviceConnection: 'richCodeNav-Token-Int'
    languages: 'csharp'
    githubServiceConnection: 'noellelc'
    environment: staging
    isPrivateFeed: false
  continueOnError: true
- script: echo Adding a final line

